CREATE TABLE [play].[Round_Hole](
	[RoundID] [INT] NOT NULL,
	[HoleID] [INT] NOT NULL,
	[Strokes] [TINYINT] NOT NULL,
 CONSTRAINT [PK_RoundID_HoleID] PRIMARY KEY CLUSTERED 
(
	[RoundID] ASC,
	[HoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [play].[Round_Hole]  WITH CHECK ADD FOREIGN KEY([HoleID])
REFERENCES [courses].[Hole] ([HoleID])
GO

ALTER TABLE [play].[Round_Hole]  WITH CHECK ADD FOREIGN KEY([RoundID])
REFERENCES [play].[Round] ([RoundID])
GO


