CREATE TABLE [play].[Round](
	[RoundID] [INT] IDENTITY(1,1) NOT NULL,
	[PlayerID] [INT] NOT NULL,
	[DatePlayed] [DATE] NOT NULL,
	[HcpAtStart] [NUMERIC](5, 2) NULL,
	[Score] [INT] NOT NULL,
	[TeeID] [INT] NOT NULL,
	[Archived] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoundID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [play].[Round] ADD  DEFAULT ((0)) FOR [Archived]
GO

ALTER TABLE [play].[Round]  WITH CHECK ADD FOREIGN KEY([PlayerID])
REFERENCES [users].[Player] ([PlayerID])
GO

ALTER TABLE [play].[Round]  WITH CHECK ADD FOREIGN KEY([TeeID])
REFERENCES [courses].[Tee] ([TeeID])
GO


