CREATE TABLE [users].[Player](
	[PlayerID] [INT] IDENTITY(1,1) NOT NULL,
	[Handle] [VARCHAR](64) NOT NULL,
	[FirstName] [VARCHAR](64) NOT NULL,
	[Surname] [VARCHAR](64) NOT NULL,
	[Handicap] [NUMERIC](5, 2) NULL,
	[Plus] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PlayerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Handle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [users].[Player] ADD  DEFAULT ((0)) FOR [Plus]
GO


