CREATE TABLE [courses].[Course](
	[CourseID] [INT] IDENTITY(1,1) NOT NULL,
	[CourseName] [VARCHAR](64) NOT NULL,
	[CourseCity] [VARCHAR](32) NOT NULL,
	[CourseState] [VARCHAR](32) NOT NULL,
	[PostalCode] [VARCHAR](8) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


