CREATE TABLE [courses].[Tee](
	[TeeID] [INT] IDENTITY(1,1) NOT NULL,
	[CourseID] [INT] NOT NULL,
	[TeeName] [VARCHAR](16) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [courses].[Tee]  WITH CHECK ADD FOREIGN KEY([CourseID])
REFERENCES [courses].[Course] ([CourseID])
GO


